### ISSUE TITLE
SVS to DICOM Conversion Resulting in Automatic Zooming Issue in Viewer

### ISSUE THREAD

**Issue by abespalko** [imi-bigpicture/wsidicomizer#101]
**Description:**
When converting SVS (Whole Slide Imaging) files to DICOM format and subsequently rendering them in various DICOM viewers such as OHIF, an unexpected behavior is observed. Upon initial rendering, the DICOM file appears to be zoomed in, and attempts to zoom out result in an automatic zoom back to the initial position. This behavior has been consistently replicated using SVS files obtained from [OpenSlide Demo](https://openslide.org/demo/). It's important to note that this issue seems isolated to SVS files, as conversion and rendering of other file formats proceed without any such complications.
<img width="1762" alt="Screenshot 2024-04-01 at 15 23 49" src="https://github.com/imi-bigpicture/wsidicomizer/assets/2743205/17ccf032-3c36-416a-a608-fd2f127805c7">

**Steps to Reproduce:**

1. Download an SVS file from the OpenSlide Demo website (e.g., https://openslide.org/demo/).
2. Convert the SVS file to DICOM format using a conversion tool (specify the tool and version used if relevant).
3. Open the resulting DICOM file in a DICOM viewer such as OHIF.
4. Observe that the image appears to be zoomed in upon initial rendering.
5. Attempt to zoom out using viewer controls.
6. Notice that the image automatically zooms back to the initial zoomed-in position.

**Expected Behavior:**

- The DICOM file should render in the viewer with the entire slide visible on the screen upon initial opening, instead of being automatically zoomed in. Example: 
<img width="1759" alt="Screenshot 2024-04-01 at 15 22 26" src="https://github.com/imi-bigpicture/wsidicomizer/assets/2743205/88ab9791-6e67-4faa-a45f-ae2ab694d2cb">

- Users should be able to freely navigate and zoom in/out of the slide as needed, without any automatic reversion to a zoomed-in position.

**Attachments:**

[Video demonstrating current behavior](https://www.loom.com/share/ea9bb6f717ea4b048154cacc6dbbcceb): This video illustrates the current behavior of the DICOM viewer when opening a converted SVS file, showcasing the automatic zooming-in phenomenon and the inability to maintain a zoomed-out view of the entire slide.

**Comment by erikogabrielsson** [comment]
Hi @abespalko and thanks for the detailed issue. 
- Could you also please share the converted DICOM files so that I can check with other readers?
- How does the conversion look for other CMU-1-slide, for example [ndpi](https://openslide.cs.cmu.edu/download/openslide-testdata/Hamamatsu/CMU-1.ndpi)?
- It could be that the reader expect more levels to be present. Can you try something like:
```python
with WsiDicomizer.open("svs file") as wsi:
    wsi.save("some path", add_missing_levels=True)
```

**Comment by abespalko** [comment]
The add_missing_levels option is now functional!

Here is the SVS slide link:
[SVS Slide](https://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-JP2K-33005.svs)

I think it would be beneficial to have that option available for the CLI as well.

**Comment by erikogabrielsson** [comment]
I will add the option to the CLI in the next release.
