### ISSUE TITLE
imagecodecs version

### ISSUE THREAD

**Issue by 11777840** [imi-bigpicture/wsidicomizer#109]
Hy Erik,

when installing the wsidicomizer (with the openslide extension), the current imagecodecs version (2024.9.22) is used. With this version, .mrxs files can no longer be converted as a ValueError is triggered:

.local/lib/python3.10/site-packages/wsidicom/codec/encoder.py", line 378, in encode return jpeg8_encode
File "imagecodecs/_jpeg8.pyx", line 161, in imagecodecs._jpeg8.jpeg8_encode
ValueError: invalid bitspersample=8

When using imagecodecs version 2024.1.1, everything works as expected. I would suggest restricting the versions.

**Comment by erikogabrielsson** [comment]
Hi @11777840 and thanks for posting this issue.

The imagecodec issue [is fixed](https://github.com/cgohlke/imagecodecs/issues/116) but there is no release yet. Meanwhile, I have released [0.21.1 of wsidicom](https://github.com/imi-bigpicture/wsidicom/releases/tag/v0.21.1) that skips the 2024.9.22 version. The imagecodec version specified in the lock file is 2024.6.1, and this has passed the tests in wsidicom.

As wsidicomizer is not directly dependent on imagecodecs I'm hesitant to add it as a dependency (to restrict the version).

**Comment by erikogabrielsson** [comment]
Released [0.15.0](https://github.com/imi-bigpicture/wsidicomizer/releases/tag/v0.15.0) with explicit restricted imagecodec version.
