### ISSUE TITLE
Use J2K instead of JP2 for codestream?

### ISSUE THREAD

**Issue by GeertLitjens** [imi-bigpicture/wsidicomizer#11]
The JPEG2000 encoder now uses JP2 format for the codestream. However, as we are writing tiles instead of actual JP2 files, shouldn't we use J2K? It is a simple flag in the imagecodecs encoder

**Comment by erikogabrielsson** [comment]
Yes, that is correct. The DICOM standard also specifies that J2K format should be used.
[For all images, including all frames of a multi-frame image, the JPEG 2000 bit stream specified in [ISO/IEC 15444-1] shall be used. The optional JP2 file format header shall NOT be included.](https://dicom.nema.org/medical/Dicom/2017c/output/chtml/part05/sect_A.4.4.html)
