### ISSUE TITLE
Do color correction during conversion.

### ISSUE THREAD

**Issue by kmuw** [imi-bigpicture/wsidicomizer#24]
Some file formats (e.g. mrxs) needs to be converted lossy, since the WSIs consist of overlapping JPG images which are stitched and blended at their seams. Thus, additional processing steps (e.g. color normalization) could be incorporated during this conversion. Color calibration slides are being used, from which color profiles for each scanner could be generated to facilitate this step.

**Comment by jesper-molin** [comment]
This would indeed remove some lossyness from the whole process if the output color space is known. However, is it known in BigPicture? I can think about three use cases:

- Standard viewing in browser based viewer (Cytomine): output space is typically sRGB
- Viewing with a fancy display and software: output space is often sRGB but not always
- Algorithmic processing: depends on algorithm, sometimes scanner color space might be wanted

Implementation-wise this is straight forward and could be done in Pillow, giving it two ICC profiles, one for the input space from a color calibration slide and one for the output space.
