### ISSUE TITLE
Label-manipulation

### ISSUE THREAD

**Issue by catweis** [imi-bigpicture/wsidicomizer#50]
First of all: Thank you very much for this great and easy-to-use tool.
May I ask where the WSI-label is retrieved in your class? The background to my question is that we want to manipulate the label.
With kind regards

**Comment by erikogabrielsson** [comment]
Hi @catweis and thanks for the feedback.

Can you tell me more on how you want to manipulate the label? Do you want to mask or replace parts in order to anonymize before conversion?
Thanks

**Comment by catweis** [comment]
Dear Erik,

thank you for your response. 
Exactly, we want to change the label to remove our lab-IDs. Or we want to replace it with a scientific ID.
This can be done before conversion or in the course of conversion.

With kind regards

**Comment by erikogabrielsson** [comment]
Thanks for the details.
So in this case I understand it would be enough to add a optional parameter, specifying a image in some format (either path to a file or a pillow image), that the converter would use instead of any label image found in the original file? I.e. we don´t have to modify the original label image?

**Comment by catweis** [comment]
Thank you for your idea. 

You are right, we do not need to modifiy the image, but we just need to exchange it.

May I ask where in you code we should add our image path and not the path to the original label?

With kind regards

 
 

Gesendet: Montag, 30. Januar 2023 um 08:50 Uhr
Von: "Erik Gabrielsson" ***@***.***>
An: "imi-bigpicture/wsidicomizer" ***@***.***>
Cc: "catweis" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [imi-bigpicture/wsidicomizer] Label-manipulation (Issue #50)


 

Thanks for the details.
So in this case I understand it would be enough to add a optional parameter, specifying a image in some format (either path to a file or a pillow image), that the converter would use instead of any label image found in the original file? I.e. we don´t have to modify the original label image?

**Comment by erikogabrielsson** [comment]
Hi catweis and thanks for the clarification,

The use case for providing a external image as label is not only relevant for wsidicomizer but also for wsidicom. So I would start with adding a classmethod to the [`Instance class`](https://github.com/imi-bigpicture/wsidicom/blob/686dbb8685552019c65affcfa9ab2f3d8a13b39d/wsidicom/instance.py#L37) to create a label instance from file.  We can then use [this instance](https://github.com/imi-bigpicture/wsidicomizer/blob/main/wsidicomizer/opentile.py#L333) and create the wsi-object (which is of WsiDicom-class).

Is this something you want to work with? Otherwise I can do it.

**Comment by catweis** [comment]
Thank you very much for your tips. So, the instance class should get a new classmethod to load an image from another path? And then for the wsi-dicomizer file there should be a new option like "no label" to load another image as label?
I will try to implement that. However, to be honest,  if you would do it, it would be much more efficient.

**Comment by catweis** [comment]
Meanwhile, I tried to modify the label. However, it is hard for me to find where the pixel data is (in your code)? My idea would be to modify directly or exchange the pixel data for the label images. 
I also thought about changing the dcm files after creation. However, I need help understanding the system behind several dcm files in the folder and, finally (when uploading to Omero) to images (one overview and the WSI).

**Comment by erikogabrielsson** [comment]
Hi catweis,
I have started working on adding a parameter to replace the label, and it seems to work. I hope to get it done during next week.

**Comment by erikogabrielsson** [comment]
> Meanwhile, I tried to modify the label. However, it is hard for me to find where the pixel data is (in your code)? My idea would be to modify directly or exchange the pixel data for the label images.

Depending on what format your original file is the pixel data will come from different classes.
> I also thought about changing the dcm files after creation. However, I need help understanding the system behind several dcm files in the folder and, finally (when uploading to Omero) to images (one overview and the WSI).

There is one dcm file for each pyramid level, label image, and overview image. So to modify the label image you would have to find the dcm file with [ImageType](https://dicom.innolitics.com/ciods/vl-whole-slide-microscopy-image/whole-slide-microscopy-image/00080008) 'LABEL'. You could then change the pixel data (most likely only one frame) and the image size (if not the same).

**Comment by erikogabrielsson** [comment]
@catweis 0.7.0 was released yesterday. You should now be able to replace the label like this:
```python
input_file = 'CMU-1.svs'
label = 'label.jpg'
output = 'with_new_label'

WsiDicomizer.convert(input_file, output, label=label)
```
