### ISSUE TITLE
Remove OpenSlide as a dependency

### ISSUE THREAD

**Issue by sarthakpati** [imi-bigpicture/wsidicomizer#60]
I would also add that openslide is not particularly important/useful for pythonic environments. It would be better to use something like tiffslide in its stead.

_Originally posted by @sarthakpati in https://github.com/imi-bigpicture/wsidicomizer/issues/7#issuecomment-1479604857_

**Comment by erikogabrielsson** [comment]
For now openslide is needed to support mirax files. Tiffslide has a work in progress to support mirax, but until it does openslide should be kept.  

However, adding support for reading from tiffslide might be worth implementing earlier, as for example the fsspec support. Im currently refactoring how wsis are opened (starting in wsidicom), but can do a simple implementation after that.

**Comment by erikogabrielsson** [comment]
Yes openslide will be moved to an extra-category.

**Comment by erikogabrielsson** [comment]
Closed with #63
