### ISSUE TITLE
Wsidicomizer command line tool not working

### ISSUE THREAD

**Issue by hhoeflin** [imi-bigpicture/wsidicomizer#64]
I installed wsidicomizer in a clean evnironment in conda (python 3.10).

Trying to run the wsidicomizer tool I get the error:

![image](https://user-images.githubusercontent.com/2385506/231684142-cc509337-13c4-4939-9988-9a99d87e5a50.png)

**Comment by erikogabrielsson** [comment]
Thanks for reporting this bug @hhoeflin. The entrypoint to the cli:s should be fixed in 0.9.1.
