### ISSUE TITLE
Install with openslide support fails

### ISSUE THREAD

**Issue by Daniel300000** [imi-bigpicture/wsidicomizer#67]
Hi!

I tried to install wsidicomizer with OpenSlide support because of Mirax (.mrxs).

When I execute the pip command as described in the README:

`pip install wsidicomizer --extras openslide`

I get the following error:

> Usage:
>   pip install [options] <requirement specifier> [package-index-options] ...
>   pip install [options] -r <requirements file> [package-index-options] ...
>   pip install [options] [-e] <vcs project url> ...
>   pip install [options] [-e] <local project path> ...
>   pip install [options] <archive url/path> ...
> 
> no such option: --extras

**Comment by erikogabrielsson** [comment]
Hi @Daniel300000 
The command described in the readme is not correct, the correct command should be:
`pip install wsidicomizer[openslide]`

**Comment by Daniel300000** [comment]
Thank you!
