### ISSUE TITLE
Upcoming OpenSlide release will change library filename

### ISSUE THREAD

**Issue by bgilbert** [imi-bigpicture/wsidicomizer#72]
The next OpenSlide release, 4.0.0, will include some incompatible API changes.  Those shouldn't affect you directly, but as a consequence, OpenSlide's [soname](https://en.wikipedia.org/wiki/Soname) will change.  This will change the library filename to `libopenslide-1.dll` on Windows, `libopenslide.1.dylib` on macOS, and `libopenslide.so.1` on Linux.  Since wsidicomizer searches for OpenSlide by filename on Windows, you may want to proactively add support for the new name so wsidicomizer will work with the new release.

For more information, see https://github.com/openslide/openslide/pull/413.  If you have any questions, please ask!

**Comment by erikogabrielsson** [comment]
Thanks @bgilbert,
I will change so that wsidicomizer searches for either libopenslide-0.dll or libopenslide-1.dll.

**Comment by erikogabrielsson** [comment]
I see in https://github.com/openslide/openslide-python/blob/fb983af551426b48d8d4ad90a70bc19ae6d297e7/openslide/lowlevel.py#L64 that openslide-python tries to load the the newer openslide library prior to the old. If both libraries are installed, do you recommend doing os.add_dll_directory() on both versions or just one?

**Comment by bgilbert** [comment]
I'd recommend adding the DLL directory for only the newer version if available, and otherwise for the older one.

**Comment by erikogabrielsson** [comment]
With #77 the new library name should also be detected.
