### ISSUE TITLE
ICC Profile in DICOM conversion

### ISSUE THREAD

**Issue by FabianHoerst** [imi-bigpicture/wsidicomizer#95]
Hello,

if I use your CLI for converting files into DICOM, the ICC profile is not transferred resulting in the Tags (0028, 2000) not present in the converted DICOM files, even though there is a profile defined in the origin files. Is there a specific flag?

Best, Fabian

**Comment by erikogabrielsson** [comment]
[This branch](https://github.com/imi-bigpicture/wsidicomizer/tree/icc-profile) adds support for taking the icc profile from compatible files. This is currently limited to files read with `OpenTile` and `OpenSlide` and primarily for Aperio svs and Ventana.

**Comment by FabianHoerst** [comment]
Thanks, I will check your branch. Maybe also `tiffinfo` could be helpful to get the icc-profile?

**Comment by erikogabrielsson** [comment]
Release [0.13.0](https://github.com/imi-bigpicture/wsidicomizer/releases/tag/v0.13.0) includes the icc-profile from supported source file.
